[program:cang-ai-task-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/cang-ai/artisan task:worker --max-retries=3
directory=/var/www/cang-ai
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startretries=3
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/cang-ai/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stopwaitsecs=3600
