[program:cang-ai-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /www/cang-ai/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --timeout=900
directory=/www/cang-ai
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startretries=3
user=www
numprocs=2
redirect_stderr=true
stdout_logfile=/www/cang-ai/storage/logs/queue.log
stdout_logfile_maxbytes=10MB
stopwaitsecs=3600
